# Generated by Django 3.2 on 2021-09-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0002_auto_20210924_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='control',
            options={'verbose_name': 'тип проверки', 'verbose_name_plural': 'типы проверок'},
        ),
        migrations.RemoveConstraint(
            model_name='act',
            name='unique_act_numbering',
        ),
        migrations.AddConstraint(
            model_name='act',
            constraint=models.UniqueConstraint(fields=('act_year', 'act_number', 'control_level'), name='unique_act_numbering'),
        ),
    ]
