# Generated by Django 3.2 on 2021-09-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0004_alter_control_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='image_before',
            field=models.ImageField(blank=True, default='apk/photo/image_not_upload.png', null=True, upload_to='apk/photo_before/', verbose_name='Фото несоответствия'),
        ),
    ]
