# Generated by Django 3.2 on 2021-09-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0005_alter_fault_image_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='image_before',
            field=models.ImageField(blank=True, null=True, upload_to='apk/photo_before/', verbose_name='Фото несоответствия'),
        ),
    ]
