# Generated by Django 3.2 on 2021-09-29 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0007_auto_20210927_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fault',
            options={'ordering': ['fault_number'], 'verbose_name': 'несоответствие', 'verbose_name_plural': 'несоответствия'},
        ),
    ]
