# Generated by Django 3.2 on 2021-10-01 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0010_alter_fault_fault_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='act',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control', to='apk.act', verbose_name='Номер акта'),
        ),
    ]
