# Generated by Django 3.2 on 2021-10-02 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0012_alter_fault_act'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fix',
            name='fault',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fault', to='apk.fault', verbose_name='Несоответствие'),
        ),
    ]
