# Generated by Django 3.2 on 2021-10-05 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0015_alter_fault_act'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('department',), 'verbose_name': 'объект проверки', 'verbose_name_plural': 'объекты проверки'},
        ),
    ]
