# Generated by Django 3.2 on 2021-10-05 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0017_auto_20211005_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='act',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faults', to='apk.act', verbose_name='Номер акта'),
        ),
        migrations.AlterField(
            model_name='fault',
            name='fault_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления несоответствия'),
        ),
    ]
