# Generated by Django 3.2 on 2021-10-05 18:20

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0020_auto_20211005_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='danger',
            field=models.BooleanField(default=False, verbose_name='Опасное событие?'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='fix_action',
            field=models.TextField(default='Данные не введены', verbose_name='Мероприятия по устранению'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='fix_deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 23, 20, 5, 710899), verbose_name='Планируемые сроки устранения'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='fix_done',
            field=models.BooleanField(default=False, verbose_name='Устранено'),
        ),
    ]
