# Generated by Django 3.2 on 2021-10-05 18:20

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0021_auto_20211005_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='fix_deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 23, 20, 52, 58284), verbose_name='Планируемые сроки устранения'),
        ),
    ]
