# Generated by Django 3.2 on 2021-10-06 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0022_alter_defect_fix_deadline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Defect',
        ),
    ]
