# Generated by Django 3.2 on 2021-10-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0023_delete_defect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='section_esupb',
            field=models.CharField(max_length=150, null=True, verbose_name='Раздел ЕСУПБ'),
        ),
    ]
