# Generated by Django 3.2 on 2021-10-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0024_alter_fault_section_esupb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='image_before',
            field=models.ImageField(blank=True, default='apk/image_not_upload.png', null=True, upload_to='apk/photo_before/', verbose_name='Фото несоответствия'),
        ),
    ]
