# Generated by Django 3.2 on 2021-10-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0025_alter_fault_image_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fix',
            name='image_after',
            field=models.ImageField(blank=True, default='apk/image_not_upload.png', null=True, upload_to='apk/photo_after/', verbose_name='Фото устранения'),
        ),
    ]
