# Generated by Django 3.2 on 2021-10-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0026_alter_fix_image_after'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='fault_date',
            field=models.DateTimeField(verbose_name='Дата добавления несоответствия'),
        ),
    ]
