# Generated by Django 3.2 on 2021-09-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='article',
            field=models.CharField(max_length=20, null=True, verbose_name='Глава источника'),
        ),
    ]
