# Generated by Django 3.2 on 2021-09-29 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_pages', '0003_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date_created'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
